services:
  - type: web
    name: Text Leech Bot
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/AshutoshGoswami24/text-leech-bot-for-render
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN "7244026647:AAGavSP5rysECMMqTwY7_me6vnD9BqDPsXw"
        sync: TRUE 
      - key: API_ID "24489231"
        sync: TRUE 
      - key: API_HASH "87077f7c5163f59bcdb67b47f1af09aa"
        sync: TRUE 
      - key: WEBHOOK
        sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
